```{r}
packages <- c("urltools","rvest","dplyr","stringr","RSQLite","ggplot2", "shiny") #Prepare a list of all the required packages
install.packages(packages) #install the required packages

#Calling all the required packages for this function
  library(RSQLite)
  library(urltools)
  library(rvest)
  library(dplyr)
  library(stringr)

city_data <- read.csv("Cities.csv", header = TRUE) #Import the file which contains the name of cities and the respective states
City_tibble <- tibble(City_name = city_data$City_name,
                        State_abbreviation= city_data$State_abbreviation) #Create a tibble containing names of all the cities within the US
  
State_tibble <- tibble(State_abbreviation = state.abb,
                        State_name= state.name) #Create a table containing names of states in the US

```
#Function to scrape data from 'indeed.com' and 'simplyhired.com' 
```{r}
indeed_job_info <- function(keyword, location){
  job_data_1 = c("Job_title","Company_name","Location","City","State") #Create a blank data frame with the required columns
  
  #This 'for' loop increnatally scrapes data from indeed.com by updating the 'start' paramenter of the indeed.com URL
  for(a in seq(0,490, by=10)){
    URL <- "https://www.indeed.com/jobs?q=%s&l=%s&start=" #This is the required URL from indeed.com
    indeed_URL <- sprintf(URL, URLencode(keyword), URLencode(location)) #Encoding the URL parameters with 'keyword' and 'location'
    parameterized_url_keyword <- param_set(indeed_URL, key = "q", value = keyword) #embedding the 'keyword' in the URL 
    parameterized_url_location <- param_set(indeed_URL, key = "l", value = location) #embedding the 'location' in the URL
    URL_1 <- paste0(parameterized_url_location, a) #pasting the parameter 'a' to increment the 'start' parameter of the URL
    HTML_code <- read_html(URL_1) #reading the HTML of the target webpage
    Job_title <- HTML_code %>% html_nodes(".jobtitle") %>% html_text(trim = T) #Extracting the job titles
    Company_name <- HTML_code %>% html_nodes(".company") %>% html_text(trim = T) #Extract the company name
    Location <- HTML_code %>% html_nodes(".location") %>% html_text(trim = T) #Extract the locations 
    City <-  as.character(gsub("\\,.*", "", Location)) #Extract the city from location 
    State = as.character(Location %>% str_extract("[A-Z]{2}")) #extracting the state abbreviation from location
    job_data <- as.data.frame(cbind(Job_title, Company_name, Location, City, State)) #combining the details of job listings in a data frame
    job_data_1 <- rbind(job_data_1, job_data) #updating the blank data frame 'job_data_1' before moving on to the next web page
    a = a + 10 #incrementing the 'start' parament of the URL
  } 
  job_data_1 = job_data_1[-1,] #removing the first row of the data frame. This is a blank row
  job_data_1 = job_data_1[!duplicated(job_data_1),] #removing the rows with duplicate values
  job_data_df = job_data_1[complete.cases(job_data_1), ] #removing the rows with missing values
#--- 'if..else' statement to manipulate the 'keyword'---#    
  kw_1 = vapply(strsplit(keyword," "), `[`, 1, FUN.VALUE=character(1))
  kw_2 = vapply(strsplit(keyword," "), `[`, 2, FUN.VALUE=character(1))
  if(is.na(kw_2)){
    kw_salary = kw_1
  } else {
    kw_salary = paste0(kw_1,"%20",kw_2)
  }
  job_data_df$Average_salary_per_year <- NA #adding a blank column 'Average_salary_per_year' to the data frame returned by the 'for' loop above
# This 'for' loop scrapes average salary information from simplyhired.com and updates the 'Average_salary_per_year' column as per the 'keyword' and the 'State'
  for (i in 1:nrow(job_data_df)){
    URL_1 = "https://www.simplyhired.com/salaries/search?q=%s&l=%s"
    salary_url_keyword <- param_set(URL_1, key = "q", value = kw_salary)
    salary_url_location <- param_set(salary_url_keyword, key = "l", value = job_data_df[i,5])
    salary_html <- read_html(salary_url_location)
    Average_salary_per_year <- salary_html %>% html_nodes(".jobposting-link") %>% html_text(trim = TRUE)
    Average_salary_per_year <- gsub("^The(.*?)is ", " ", Average_salary_per_year)
    Average_salary_per_year = substr(Average_salary_per_year,1,nchar(Average_salary_per_year)-2)
    job_data_df[i,6] = Average_salary_per_year
    i = i + 1}
  job_data_df$Average_salary_per_year <- as.numeric(gsub('[$,]', '', job_data_df$Average_salary_per_year)) #dropping the redundant characters from the 'Average_salary_per_year' column, and converting the values to numeric for ease of analysis 
  write.csv(job_data_df, file = "Job_data.csv") #copying the final data frame to the local drive
}

```
#Use the function to scrap data as per the keyword and location
```{r}
indeed_job_info('Data Analyst', 'US') #Getting data for a sample keyword and location. This takes a few minutes. Incase of an error, reduce the number of iterations in the 'for' loop in the function above, and run the code. i.e change 490 to 400 or 300.
job_data_df = as.data.frame(read.csv("Job_data.csv", header = T)) #importing the file returned by the function from the local drive
job_data_df = job_data_df[,-1] #dropping the first column containing serial numbers for the rows
View(job_data_df) #view the data frame in the R environment
```
#Insert the scraped data into a relational database
```{r}
#################################
#      BUILDING A DATABSE       #
#################################

db <- dbConnect(SQLite(), dbname="Jobs_database.sqlite") #Creating a database and establishing a connection between R and that database
  
  #Creating a table for the States 
  dbRemoveTable(conn = db, 'State')
  dbGetQuery(db, "CREATE TABLE State
  (
    StateId INTEGER PRIMARY KEY, -- Autoincrement
    State_abbreviation TEXT,
    State_name TEXT
  )")
  
dbWriteTable(conn = db, name = "State", value = State_tibble, row.names = FALSE, append = TRUE) #Inserting data in the 'State' tibble
dbReadTable(db, 'State')
#----------------------------------------------------------------------------------------------------  
  #Creating a table for the Cities 
  dbRemoveTable(conn = db, 'City')
  dbGetQuery(db, "CREATE TABLE City
  (
    CityId INTEGER PRIMARY KEY, -- Autoincrement
    City_name TEXT,
    State_abbreviation TEXT
  )")

dbWriteTable(conn = db, name = "City", value = City_tibble, row.names = FALSE, append = TRUE) #Inserting data in the 'City' tibble
dbReadTable(db, 'City')
#----------------------------------------------------------------------------------------------------  
  #Creating a table for the Job title
  dbRemoveTable(conn = db, 'Job_Title')
  dbGetQuery(db, "CREATE TABLE Job_Title
  (
    Job_titleId INTEGER PRIMARY KEY, --Autoincrement
    Job_title_name TEXT
  )")
  
Job_title_tibble <- tibble(Job_title_name = job_data_df$Job_title)
dbWriteTable(conn = db, name = "Job_title", value = Job_title_tibble, row.names = FALSE, append = TRUE)
dbReadTable(db, 'Job_Title')
#-----------------------------------------------------------------------------------------------------

#Creating a table for Companies
  dbRemoveTable(conn = db, 'Company')
  dbGetQuery(db, "CREATE TABLE Company
  (
    Company_Id INTEGER PRIMARY KEY, --Autoincrement
    Company_name TEXT
  )")
  
Company_tibble <- tibble(Company_name = job_data_df$Company_name)
dbWriteTable(conn = db, name = "Company", value = Company_tibble, row.names = FALSE, append = TRUE)
dbReadTable(db, 'Company')
#-----------------------------------------------------------------------------------------------------
  
#Creating a table for the Job listings
  dbRemoveTable(conn = db, 'Job_listings')
  dbGetQuery(db, "CREATE TABLE Job_listings
  (
    Job_listingId INTEGER PRIMARY KEY, --Autoincrement
    Job_title_name TEXT,
    Company_name TEXT,
    City_name TEXT,
    State_abbreviation TEXT,
    Average_salary INTEGER
  )")

job_data_tibble <- tibble(Job_title_name = job_data_df$Job_title,
                          Company_name = job_data_df$Company_name,
                          City_name = job_data_df$City,
                          State_abbreviation = job_data_df$State,
                          Average_salary = job_data_df$Average_salary_per_year)
  
dbWriteTable(conn = db, name = "Job_listings", value = job_data_tibble, row.names = FALSE, append = TRUE)
dbReadTable(db, 'Job_listings')
#-----------------------------------------------------------------------------------------------------
```
...
#Write queries to answer questions about the data
```{r}
#1.Top 10 companies in the US with the highest number of jobs as per the keyword
company_plot_data <- as.data.frame(dbGetQuery(db, "SELECT DISTINCT(Company_name), COUNT(*) 
                                   FROM Job_listings
                                   GROUP BY Company_name
                                   ORDER BY COUNT(*) DESC
                                   LIMIT 10"))
company_plot_data

#2. Top 10 Cities in the US with the highest number of jobs as per the keyword
city_plot_data <- as.data.frame(dbGetQuery(db, "SELECT DISTINCT(City_name), COUNT(*) 
                                FROM Job_listings
                                GROUP BY City_name
                                ORDER BY COUNT(*) DESC
                                LIMIT 10"))
city_plot_data

#3. Top 10 States in the US with the highest number of jobs as per the keyword
states_plot_data <- as.data.frame(dbGetQuery(db, "SELECT DISTINCT(State.State_name), COUNT(*) 
                                  FROM Job_listings JOIN State
                                  ON Job_listings.State_abbreviation = State.State_abbreviation
                                  GROUP BY State.State_name
                                  ORDER BY COUNT(*) DESC
                                  LIMIT 10"))
states_plot_data

#4. Top 10 companies in the US with the highest salaries as per the keyword
company_salary_plot_data <- as.data.frame(dbGetQuery(db, "SELECT Company_name, Average_salary
                                                FROM Job_Listings
                                                ORDER BY Average_salary DESC
                                                LIMIT 10"))
company_salary_plot_data

#5. Top 10 states in the US with the highest salaries as per the keyword
state_salary_plot_data <- as.data.frame(dbGetQuery(db, "SELECT DISTINCT(State.State_name), Average_salary
                                                FROM Job_Listings JOIN State
                                                ON Job_listings.State_abbreviation = State.State_abbreviation
                                                ORDER BY Average_salary DESC
                                                LIMIT 10"))

state_salary_plot_data

#6.Top 5 job titles in the US with the highest salaries as per the keyword
JobTitle_salary_plot_data <- as.data.frame(dbGetQuery(db, "SELECT DISTINCT(Job_title_name), Average_salary
                                                FROM Job_Listings
                                                ORDER BY Average_salary DESC
                                                LIMIT 10"))

JobTitle_salary_plot_data

```

#Plots
```{r}
#1.Top 10 companies in the US with the highest number of jobs as per the keyword
library(ggplot2)
colnames(company_plot_data) <- c("Company_name", "Number_of_jobs")

company_plot <- ggplot(data=company_plot_data, aes(x = reorder(Company_name, -Number_of_jobs), y = Number_of_jobs)) + geom_bar(stat="identity", width = 0.5, fill="dark green") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + geom_text(aes(label=Number_of_jobs), vjust=-0.3, size=3.5) + ggtitle("Top 10 comapnies with the most number of jobs")

company_plot
#--------------------------------------------------------------------------------
#2. Top 10 Cities in the US with the highest number of jobs as per the keyword
colnames(city_plot_data) <- c("City", "Number_of_jobs")

city_plot <- ggplot(data=city_plot_data, aes(x = reorder(City, -Number_of_jobs), y = Number_of_jobs)) + geom_bar(stat="identity", width = 0.5, fill="dark red") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + geom_text(aes(label=Number_of_jobs), vjust=-0.3, size=3.5) + ggtitle("Top 10 cities with the most number of jobs")

city_plot
#--------------------------------------------------------------------------------

#3. Top 10 States in the US with the highest number of jobs as per the keyword
colnames(states_plot_data) <- c("State", "Number_of_jobs")
state_plot <- ggplot(data=states_plot_data, aes(x = reorder(State, -Number_of_jobs), y = Number_of_jobs)) + geom_bar(stat="identity", width = 0.5, fill="steelblue") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + geom_text(aes(label=Number_of_jobs), vjust=-0.3, size=3.5) + ggtitle("Top 10 states with the most number of jobs")

state_plot
#--------------------------------------------------------------------------------

#4. Top 10 companies in the US with the highest salaries as per the keyword
colnames(company_salary_plot_data) <- c("Company_name", "Average_salary")

company_salary_plot <- ggplot(data=company_salary_plot_data, aes(x = reorder(Company_name, -Average_salary), y = Average_salary)) + geom_bar(stat="identity", width = 0.5, fill="dark green") + theme(axis.text.x = element_text(angle = 45, hjust = 1), text = element_text(size = 15)) + geom_text(aes(label=Average_salary), vjust=-0.3, size=4, angle = 45, hjust = 0) + xlab("Name of the company")+ ylab("Average salary per year")

company_salary_plot

#--------------------------------------------------------------------------------
#5. Top 10 states in the US with the highest salaries as per the keyword
colnames(state_salary_plot_data) <- c("State_name", "Average_salary")

State_salary_plot <- ggplot(data=state_salary_plot_data, aes(x = reorder(State_name, -Average_salary), y = Average_salary)) + geom_bar(stat="identity", width = 0.5, fill="steelblue") + theme(axis.text.x = element_text(angle = 45, hjust = 1), text = element_text(size = 15)) + geom_text(aes(label=Average_salary), vjust=-0.3, size=4, angle = 45) + xlab("State abbreviation")+ ylab("Average salary per year")

State_salary_plot
#--------------------------------------------------------------------------------
#6. Top 10 job titles in the US with the highest salaries as per the keyword
colnames(JobTitle_salary_plot_data) <- c("Job_title", "Average_salary")

JobTitle_salary_plot <- ggplot(data=JobTitle_salary_plot_data, aes(x = reorder(Job_title,-Average_salary), y = Average_salary)) + geom_bar(stat="identity", width = 0.5, fill="brown") + theme(axis.text.x = element_text(angle = 45, hjust = 1), text = element_text(size = 15)) + geom_text(aes(label=Average_salary), vjust=-0.3, size=4, angle = 45) + xlab("Job title")+ ylab("Average salary per year")

JobTitle_salary_plot #Some of the bars overlap each other because even though the 'Average_salary_per_year' is different, the 'Job_title' is the same.
```

#Shiny Application
```{r}
library(shiny)
ui <- fluidPage(
   titlePanel("Analysis of job listings on 'Indeed.com'"),
  tabsetPanel(
    tabPanel("Top 10 Companies - Number of jobs", plotOutput("company_plot", width = "80%", height = "600px")),
    tabPanel("Top 10 Cities - Number of jobs",plotOutput("city_plot", width = "80%", height = "600px")),
    tabPanel("Top 10 States - Number of jobs",plotOutput("state_plot", width = "80%", height = "600px")),
    tabPanel("Top 10 Companies - Highest salary",plotOutput("company_salary_plot", width = "80%", height = "600px")),
    tabPanel("Top 10 States - Highest salary",plotOutput("State_salary_plot", width = "80%", height = "600px")),
    tabPanel("Top 10 Job titles - Highest salary",plotOutput("JobTitle_salary_plot", width = "80%", height = "600px")) 
  )
)

server <- function(input, output){
 output$company_plot <- renderPlot({ggplot(data=company_plot_data, aes(x = reorder(Company_name, -Number_of_jobs), y = Number_of_jobs)) + geom_bar(stat="identity", width = 0.5, fill="dark green") + theme(axis.text.x = element_text(angle = 45, hjust = 1), text = element_text(size = 20)) + geom_text(aes(label=Number_of_jobs), vjust=-0.3, size=5) + xlab("Company")+ ylab("Number of jobs")}) 
 
 output$city_plot <- renderPlot({ggplot(data=city_plot_data, aes(x = reorder(City, -Number_of_jobs), y = Number_of_jobs)) + geom_bar(stat="identity", width = 0.5, fill="dark red") + theme(axis.text.x = element_text(angle = 45, hjust = 1), text = element_text(size = 20)) + geom_text(aes(label=Number_of_jobs), vjust=-0.3, size=5) + xlab("City")+ ylab("Number of jobs")}) 
 
 output$state_plot <- renderPlot({ggplot(data=states_plot_data, aes(x = reorder(State, -Number_of_jobs), y = Number_of_jobs)) + geom_bar(stat="identity", width = 0.5, fill="steelblue") + theme(axis.text.x = element_text(angle = 45, hjust = 1), text = element_text(size = 20)) + geom_text(aes(label=Number_of_jobs), vjust=-0.3, size=5) + xlab("State")+ ylab("Number of jobs")})
 
 output$company_salary_plot <- renderPlot({ggplot(data=company_salary_plot_data, aes(x = reorder(Company_name, -Average_salary), y = Average_salary)) + geom_bar(stat="identity", width = 0.5, fill="limegreen") + theme(axis.text.x = element_text(angle = 45, hjust = 1), text = element_text(size = 20)) + geom_text(aes(label=Average_salary), vjust=-0.3, size=5, angle = 45, hjust = 1) + xlab("Company")+ ylab("Average salary per year in USD")})
 
output$State_salary_plot <- renderPlot({ggplot(data=state_salary_plot_data, aes(x = reorder(State_name, -Average_salary), y = Average_salary)) + geom_bar(stat="identity", width = 0.5, fill="steelblue1") + theme(axis.text.x = element_text(angle = 45, hjust = 1), text = element_text(size = 20)) + geom_text(aes(label=Average_salary), vjust=-0.3, size=5, angle = 45, hjust = 1) + xlab("State")+ ylab("Average salary per year in USD")})

output$JobTitle_salary_plot <- renderPlot({ggplot(data=JobTitle_salary_plot_data, aes(x = reorder(Job_title, -Average_salary), y = JobTitle_salary_plot_data$Average_salary)) + geom_bar(stat="identity", width = 0.5, fill="orange") + theme(axis.text.x = element_text(angle = 45, hjust = 1), text = element_text(size = 20)) + geom_text(aes(label=Average_salary), vjust=-0.3, size=5, angle = 45, hjust = 1) + xlab("Job title")+ ylab("Average salary per year in USD")})
}
shinyApp(ui = ui, server = server)
```

